---
  - name: download repository apt key
    get_url:
      url: https://download.sublimetext.com/sublimehq-pub.gpg
      dest: ~/sublimehq-pub.gpg

  - name: add repository apt key
    apt_key:
      file: ~/sublimehq-pub.gpg
      state: present

  - name: create apt source list
    copy:
      content: "deb https://download.sublimetext.com/ apt/stable/"
      dest: /etc/apt/sources.list.d/sublime-text.list

  - name: install sublime text
    apt:
      name=sublime-text
      state=installed
      update_cache=yes

  - name: remove apt key temp file
    file:
      path: ~/sublimehq-pub.gpg
      state: absent
